tracespace/tracespace

- API.md
- README.md
Changes mainly to API.md to make it more editable.
The only thing that might be of note is that the Travis build shield in the README is changed to always reflect the master branch build status (instead of the most recent Travis build, which could be a branch or PR build). Not sure if this wasn't intentional.
> Fixup docs

- README.md
Per #14, it's kinda weird our example image in the README is a png file. Replaces it with not one but two SVGs.
Also adds a couple more badges because badges.
> Use SVG renders in README and ADD MORE BADGES (fixes #14)

- .zuul.yml
- README.md
- package.json
This PR updates pcb-stackup-core to latest (v2.0.1). It also switches from coveralls to codecov for coverage because coveralls has been causing CI builds to fail.
Should probably be considered a major because the pcb-stackup-core bump is major.
> Upgrade pcb-stackup-core to v2

- README.md
Gitter room has been set up at https://gitter.im/tracespace/pcb-stackup. This PR adds a link to the README.
> Add gitter badge to readme (fixes #34)

- .zuul.yml
- index.js
- package.json
- test.js
Looks like passing back the "layers" cache isn't working as we intended. I think it's giving back empty (invalid?) SVGs on the second pass. 
I was experiencing this when trying to make use of it in Kitnic and modified the tests to verify. They fail with these modifications.  [Full test output is here](https://gist.github.com/kasbah/0164cce32e262ad3b800cc89c18d5dfe).
As always, any insight appreciated.
> Make layers cache actually work

- API.md
Realized I forgot about this a second after I merged. 
https://github.com/tracespace/pcb-stackup/blob/document-converter/API.md#layer--object
> Document the converter property in layer object

- packages/gerber-plotter/lib/path-graph.js
- packages/gerber-plotter/test/path-graph_test.js
I am looking at the regression observed in the outlines drawn from the bus-pirate ~~and maulwurf~~ example boards. This is most likely something to do with trying to use the closest point for outline gap filling which was added to the gerber-plotter recently and seemed to be working well for the usbvil board.
> fix(gerber-plotter): Board outline regression

- packages/fixtures/gerber-filenames.json
- packages/whats-that-gerber/README.md
- packages/whats-that-gerber/index.js
I know you are re-writing whats-that-gerber in #77 but I thought I would quickly fix this as it's kind of ruining [this board on Kitspace](https://kitspace.org/boards/github.com/robotsrulz/sp_adapter/). At one point we had good enough DipTrace support accidentally that I didn't even notice it was DipTrace but it's slowly been eroded away over time.
> feat(whats-that-gerber): Add support for diptrace filenames

- README.md
- packages/cli/README.md
- packages/fixtures/README.md
- packages/gerber-parser/README.md
- packages/gerber-plotter/README.md
- packages/gerber-to-svg/README.md
- packages/pcb-stackup-core/README.md
- packages/pcb-stackup/README.md
- packages/whats-that-gerber/README.md
- packages/xml-id/README.md
This PR switches all the badges from shields.io to badgen.net and cleans up / aligns their usage. Importantly, we now display badges for npm@latest _and_ npm@next, which should hopefully make this extended prerelease period a little less confusing.
> docs: Switch badges to badgen and add npm@next badges

- package-lock.json
- package.json
`har-validator` is in our lockfile at 5.1.2, which was unpublished (See ahmadnassri/node-har-validator#112), breaking our CI builds.
`har-validator` was a sub(-sub-sub)-dependency of lerna and codecov, so they were both upgraded to pick up the necessary changes.
> chore(deps): Upgrade lerna/codecov to lock new version of har-validator

- packages/gerber-parser/lib/_parse-drill.js
- packages/gerber-parser/test/gerber-parser_drill_test.js
Ran into a drill file recently that started off like this:
```
M48
M72,LZ
```
I don't know that this is official syntax, but this adds support for files like it.
Note this is completely untested. I started writing tests, but couldn't figure out how to get them to run. It appears there's a bunch of unmarked dependencies required to get a test environment working.
> Added support for excellon drill files w/ leading/trailing set in M71/M72 line

- .eslintignore
- .eslintrc.js
- package-lock.json
- package.json
- packages/cli/README.md
- packages/cli/scripts/docs.js
- packages/gerber-parser/index.d.ts
- packages/gerber-parser/package.json
- packages/gerber-plotter/index.d.ts
- packages/gerber-plotter/package.json
- packages/gerber-to-svg/index.d.ts
- packages/gerber-to-svg/package.json
- packages/pcb-stackup-core/index.d.ts
- packages/pcb-stackup-core/package.json
- packages/pcb-stackup/index.d.ts
- packages/pcb-stackup/package.json
- packages/whats-that-gerber/index.d.ts
- packages/whats-that-gerber/package.json
- packages/xml-id/index.d.ts
- packages/xml-id/package.json
- tsconfig.json
~Blocked by #102; this PR to be rebased over `next` once it's merged.~
This PR adds Typescript definitions to all consumable modules. The upcoming viewer rewrite is in Typescript (see mcous/tracespace#1), so this seemed like a good thing to do.
It also sets up eslint and prettier to handle Typescript. The unrelated `.md` changes are a side-effect of being better about running prettier on everything. Was easier to include them here than do a separate PR, but sorry for the noise regardless.
> feat: Add typescript definitions to all consumable modules

- .travis.yml
- apps/view/package.json
- apps/www/package.json
- package-lock.json
- package.json
- scripts/publish-to-s3.js
This PR adds CI configuration to deploy new app versions (currently just `view`) as part of the CI build process. This links app releases to library releases, which may not scale in the future, but for now it's a nice way to make sure the viewer is _always_ using the latest rendering logic.
Current contents of <https://staging.tracespace.io> were set by this branch's CI build (prior to fixup commit switching staging branch to `next`).
BREAKING CHANGE: Node v6 dropped from CI testing matrix. Node v6 is EOL in a month, so I'd rather make the break now while 4.0.0 is prerelease and can still collect breaks.
> ci(travis): Set up deployment to S3 from Travis

- package.json
- packages/gerber-plotter/integration/gerber-plotter-snapshot.test.js
- packages/gerber-to-svg/index.js
- packages/gerber-to-svg/integration/gerber-to-svg-snapshot.test.js
- packages/gerber-to-svg/test/gerber-to-svg_test.js
- packages/pcb-stackup-core/integration/pcb-stackup-core-snapshot.test.js
- packages/pcb-stackup/integration/pcb-stackup-snapshot.test.js
While working on #180, I found a typo in gerber-to-svg that was preventing the `done` callback from being properly registered if the `options` object was skipped. This PR fixes that bug
> fix(gerber-to-svg): Allow options parameter to be skipped

- packages/gerber-plotter/lib/plotter.js
- packages/gerber-plotter/test/gerber-plotter_test.js
According to the [gerber-plotter docs](https://github.com/tracespace/tracespace/blob/master/packages/gerber-plotter/API.md#block-repeat-objects):
> A repeat object with a zero-length offsets array means repeating has been turned off.
Instead of this, the plotter was emitting a repeat object with an offsets array of `[[0,0]]`. This PR changes the plotter behavior to match its documentation (and the expectations of gerber-to-svg).
Closes #81
> fix(gerber-plotter): Emit correct 'repeat' object on steprepeat disable

- .travis.yml
- README.md
- package.json
#180 broke the example file upload to `npm` because I forgot to include `npm run example` in the combined build and publish job. This PR fixes that oversight and improves the build docs slightly
> ci(travis): Fix example file deploys

- renovate.json
Based on the PRs coming in, I think it's fine to go ahead and group all dev dependencies into one group to reduce the number of PRs / commits for these upgrades
> ci(renovate): Combine all devDependencies into one Renovate group

- .mocharc.js
- apps/view/src/render/models.ts
- packages/fixtures/gerber-filenames.json
- packages/whats-that-gerber/index.js
- packages/whats-that-gerber/lib/constants.js
- packages/whats-that-gerber/lib/layer-types.js
- packages/whats-that-gerber/lib/matchers.js
Closes #246, closes #248. See those tickets for background.
Importantly for future work: this PR sets up a whats-that-gerber blacklist. At the moment it's causing wtg to ignore Eagle metadata files (.gpi, .dri) but hopefully can be extended for other stuff in the future that are commonly included in board bundles that could cause false hits with the Gerber matchers
> fix(whats-that-gerber): Add support for PCB:NG Eagle, .gbx, and .art

- renovate.json
Given my contribution patterns to this repo (i.e. whenever I have free time), there are too many Renovate PRs for me to merge without burning all my tracespace time on dependency management. This PR groups all bumps together into one PR per dependency type.
I think this will be more manageable and is honestly what I usually end up doing manually anyway
> chore(renovate): Group all dependency updates together

- packages/gerber-parser/API.md
- packages/gerber-parser/lib/_parse-drill.js
- packages/gerber-parser/test/gerber-parser_drill_test.js
Hi,
My company is using Tracespace for parsing Altium Gerber files and came across the need to differentiate between plated and non-plated holes.
We thought you might like to include this change in the main Tracespace codebase.
Example Drill file:
```
M48
;Layer_Color=9474304
;FILE_FORMAT=4:4
METRIC,TZ
;TYPE=PLATED
T1F00S00C0.3000
T2F00S00C0.9000
...
```
This change will add the 'plating' property to the output hole definitions:
```
{
"tools": {
"T01": {
"id": "T01",
"size": 0.2,
"plating": "PTH"
},
...
}
```
> Identify Plated/Non Plated holes in Drill File

- packages/pcb-stackup/README.md
`path` is not defined in this context, change to use `filename` instead
> doc(pcb-stackup): fix usage example in README

- apps/view/src/BoardDisplay/index.tsx
Previously, when one of the board renders was selected, the layers render was set to `display: none`. This made any `<mask>`s referenced in the board renders fail to load, because the `mask="url(#some_mask_id)"` attribute would no longer resolve.
This PR switches the hiding mechanism for the layers view from `display: none` to clipping.
Fixes #303
> fix(view): Ensure layer defs are accessible to <mask>s in board renders

- .gitignore
.DS_Store is a file that stores custom attributes of its containing folder, such as the position of
icons or the choice of a background image. The files sometimes get automatically created and are
meaningless to the project and thus must be excluded.
> chore(.gitignore): Add MacOS system files .DS_Store to be ignored

- packages/cli/lib/cli.js
- packages/cli/lib/options.js
- packages/cli/lib/resolve.js
- packages/cli/package.json
The input file resolution for the CLI was a little too clever, and attempted to resolve everything to absolute paths while replacing `~`s with the home directory and then passing everything into `globby` to also get any glob patterns. Unfortunately, [`globby` does not support Windows file paths](https://github.com/sindresorhus/globby#api), which meant that on Windows, any input file would be resolved to an absolute Windows path, which `globby` would fail to match with any files.
This PR:
- Gets rid of the explicit resolve to `process.cwd` because it's redundant
- Only passes things that look like globs to globby, otherwise treats them like files
- Makes sure that any glob patterns have their path separators switched to POSIX-style
Fixes #327
> fix(cli): fix cli file path resolution on Windows

- .github/workflows/publish.yml
- CHANGELOG.md
- README.md
- apps/view/CHANGELOG.md
- apps/view/package.json
- config/CHANGELOG.md
- config/package.json
- lerna.json
- package.json
- packages/cli/CHANGELOG.md
- packages/cli/package.json
- packages/fixtures/CHANGELOG.md
- packages/fixtures/package.json
- packages/gerber-parser/CHANGELOG.md
- packages/gerber-parser/package.json
- packages/gerber-plotter/CHANGELOG.md
- packages/gerber-plotter/package.json
- packages/gerber-to-svg/CHANGELOG.md
- packages/gerber-to-svg/package.json
- packages/parser/CHANGELOG.md
- packages/parser/README.md
- packages/parser/package.json
- packages/pcb-stackup-core/CHANGELOG.md
- packages/pcb-stackup-core/package.json
- packages/pcb-stackup/CHANGELOG.md
- packages/pcb-stackup/package.json
- packages/whats-that-gerber/CHANGELOG.md
- packages/whats-that-gerber/package.json
- packages/xml-id/CHANGELOG.md
- packages/xml-id/package.json
This PR updates CI configuration and documentation to start publishing v5 pre-releases under the `next` tag on npm. So far, this includes:
- TypeScript rewrite of whats-that-gerber
- TypeScript rewrite of @tracespace/xml-id
- gerber-parser replacement library @tracespace/parser
> Start publishing v5 pre-releases

- packages/gerber-parser/lib/_parse-gerber.js
- packages/gerber-parser/lib/_parse-macro-block.js
- packages/gerber-parser/test/gerber-parser_gerber_test.js
- packages/gerber-plotter/lib/_pad-shape.js
- packages/gerber-plotter/test/gerber-plotter_test.js
This PR fixes #345. There were three separate bugs that combined to produce the bad output reported:
- The parser did not know how to handle negative tool modifiers in `%AD` tool definitions
- The parser, for outline primitives in particular, did not allow macro expressions to be used as parameters to the primitive
- The plotter did not know how to plot an outline primitive using macro expressions as its parameters
> fix: accept negative tool mods and macro expression args for outline primities

- packages/gerber-plotter/index.d.ts
More types for the output of the plotter. Be great to get them into main.
Voltera's App uses the plotter directly and I've been using a local patch until now.
> fix(types): define more types for gerber-plotter

- packages/gerber-parser/lib/_parse-gerber.js
- packages/gerber-parser/test/gerber-parser_gerber_test.js
Cadence Allegro include the units on the same line as the format.  The gerber spec says
> There can be only one extended code command between each pair of ‘%’ delimiters
but I believe the goal of this repo is to handle variations (as long as they are not harmful)
Here's what it looks like (copied from a customer's file):
```
G04 File Origin:  Cadence Allegro 17.2-S032*
...
%FSLAX25Y25*MOMM*%
```
I commented the code and the test, happy to mod as needed
> fix(parser): accept units on same line as format

- packages/gerber-plotter/lib/_operate.js
- packages/gerber-plotter/test/gerber-plotter_test.js
A conditional in the plotter's `_operate` function was in the incorrect order, preventing valid region arc outlines from being drawn if there was no tool set. This PR improves that guard to allow arcs for missing tools in region mode.
Fixes #355
> fix(gerber-plotter): allow unset tool when drawing region arcs

- packages/gerber-parser/lib/_parse-gerber.js
Prevent Object Attributes (TO) attributes from being parsed as operations or commands
Fixes https://github.com/tracespace/tracespace/issues/375
> Prevent parse-gerber to parse object attributes

- packages/gerber-plotter/lib/plotter.js
- packages/gerber-plotter/test/gerber-plotter_test.js
The `v4` plotter no-ops when it receives tool definition commands for tools that are already defined. Drill files may repeat tool definitions as a way of calling out tool changes, for some reason.
This PR changes the behavior of the plotter to process the definition rather than ignore it. It still triggers a warning, but it will now process the definition and, importantly, change the active tool.
Closes #378
> fix(gerber-plotter): do not ignore duplicate tool definitions
